# Generated by Django 6.0.7 on 2026-08-03 13:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_adminauditlog_groqapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerRoadmapProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roadmap_data', models.JSONField(default=dict)),
                ('jd_text', models.TextField(blank=True, default='')),
                ('completed_weeks', models.JSONField(default=list)),
                ('quiz_scores', models.JSONField(default=dict)),
                ('quiz_submitted', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seeker', models.OneToOneField(db_column='seeker_id', on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_progress', to='api.jobseekeraccount')),
            ],
            options={
                'db_table': 'seeker_roadmap_progress',
            },
        ),
    ]
